AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple backend for handling events sent from Twilio.
Metadata:
  Name: twiliosimpleblueprint
Resources:
  twiliosimpleblueprint:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: A simple backend for handling events sent from Twilio.
      MemorySize: 128
      Timeout: 15
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - EC2VPNDescribePolicy: {}
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
