# https://github.com/psf/black/blob/master/.pre-commit-config.yaml
repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      language: system
      require_serial: true
      types: [python]
