# Enable container based builds
sudo: false
dist: xenial   # required for Python >= 3.7
language: python

matrix:
  include:
    - python: 3.8
      env:
        - TOXENV=py38
    - python: 3.7
      env:
        - TOXENV=py37
    - python: 3.6
      env:
        - TOXENV=py36
    - python: 2.7
      env:
        - TOXENV=py27


install:
# Install the code requirements
- >
  if [ $TOXENV = py27 ]; then
    mkdir $HOME/bin-black
    # make sure we are using the same black version as in dev.txt
    wget -O $HOME/bin-black/black https://github.com/python/black/releases/download/20.8b1/black
    chmod +x $HOME/bin-black/black
    export PATH=$PATH:$HOME/bin-black
    black --version
  fi
- make init

# Install Docs requirements

script:
# Runs unit tests
- tox
