# Enable container based builds
sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env:
        - TOXENV=py36
    - python: 2.7
      env:
        - TOXENV=py27


install:
# Install the code requirements
- make init

# Install Docs requirements

script:
# Runs unit tests
- tox
