version: 1.0.{build}
image: Ubuntu

environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

install:
- export PATH=/home/appveyor/.local/bin:$PATH
- python -m pip install --upgrade pip awscli boto3 setuptools
- pip install -e '.[dev]' --use-feature=2020-resolver

test_script:
- tox
