version: 0.1
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file template.yaml --s3-bucket serverless-ss 
                                   --output-template-file template.yaml
artifacts:
  type: zip
  files:
    - template.yaml
