Transform: AWS::Serverless-2016-10-31
Resources:
  SuperCoolAPI:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      SchemaInline: |
        type Mutation {
          addTodo(id: ID!, name: String, description: String, priority: Int): Todo
        }
      Visibility: PRIVATE
      OwnerContact: blah-blah
      IntrospectionConfig: DISABLED
      QueryDepthLimit: 10
      ResolverCountLimit: 100
      Auth:
        Type: AWS_IAM
