Transform: AWS::Serverless-2016-10-31
Resources:
  SuperCoolAPI:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      Name: SomeApi
      SchemaInline: |
        type Mutation {
          addTodo(id: ID!, name: String, description: String, priority: Int): Todo
        }
      Auth:
        Type: AWS_IAM
      DynamoDBDataSources:
        MyDataSource:
          Name: MyDataSource
      Functions:
        MyFunction:
          CodeInline: this is my epic code
          DataSourceName: MyDataSource
          Runtime:
            Name: some-runtime
            Version: 1.2.3
