version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "prads-epic-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18nr0g14pv4d2"
s3_prefix = "prads-epic-api"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
