Transform: AWS::Serverless-2016-10-31
Resources:
  SuperCoolAPI:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      Name: SomeApi
      SchemaInline: |
        type Mutation {
          addTodo(id: ID!, name: String, description: String, priority: Int): Todo
        }
      XrayEnabled: true
      Auth:
        Type: AWS_IAM
      Tags:
        key1: value1
        key2: value2
      DynamoDBDataSources:
        MyDataSource:
          Name: MyDataSource
          TableName: SomeTable
          ServiceRoleArn: SomeRoleArn
      AppSyncResolvers:
        Mutation:
          saveNote:
            FieldName: blah
            DataSourceName: some-data-source
            MaxBatchSize: 10
            Runtime:
              Name: some-runtime
              Version: 1.2.3
            Caching:
              Ttl: 20
              CachingKeys:
              - key1
              - key2
            Functions:
            - MyFunction:
                InlineCode: this is my epic code
                DataSource: MyDataSource
                Runtime:
                  Name: some-runtime
                  Version: 1.2.3