Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ${codeuri}
      MemorySize: 128
      Tags:
        TagKey1: TagValue1
        TagKey2: ''
Metadata:
  SamTransformTest: true
