Parameters:
  CanaryName:
    Type: String
    Default: integration-test
    MaxLength: 21
Resources:
  # role and role permission created for now so that canary will develop, won't be needed in the future when feature to
  # automatically create role from serverless canary is added
  SyntheticsCanary:
    Type: AWS::Serverless::Canary
    Properties:
      FunctionName:
        Fn::Sub: ${CanaryName}
      Handler: pageLoadBlueprint.handler
      InlineCode: |
        def handler(event, context):
          print("Hello, world!")
      Runtime: syn-python-selenium-1.0
      StartCanaryAfterCreation: true
      Schedule:
        Expression: rate(0 minute)
      Tags:
        TagKey1: TagValue1
        TagKey2: ""
