AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple email filter for protection against spam and viruses as well as DKIM and SPF failures.
Metadata:
  Name: inboundsesspamfilter
Parameters: 
    IdentityNameParameter: 
      Type: String
Resources:
  inboundsesspamfilter:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: >-
        A simple email filter for protection against spam and viruses as well as DKIM and SPF failures.
      MemorySize: 128
      Timeout: 10
      Policies:
        - SESSendBouncePolicy:
            IdentityName: IdentityNameParameter
      Environment:
        Variables:
          emailDomain: <enter value here>
