Outputs:
  ApiEndpoint:
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/MyNewStageName
Resources:
  MyApi:
    Properties:
      Mode: overwrite
      StageName: MyNewStageName
    Type: AWS::Serverless::Api
  TestFunction:
    Properties:
      AutoPublishAlias: live
      Events:
        Get:
          Properties:
            Method: get
            Path: /get
            RestApiId:
              Ref: MyApi
          Type: Api
        Put:
          Properties:
            Method: put
            Path: /put
            RestApiId:
              Ref: MyApi
          Type: Api
      Handler: index.handler
      InlineCode: "import json\ndef handler(event, context):\n  return {'statusCode':\
        \ 200, 'body': json.dumps('Hello World!')}\n"
      Runtime: python3.6
    Type: AWS::Serverless::Function
