AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple Hello World Serverless project
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.amazonaws.examples.HelloWorld
      CodeUri: ./target/HelloWorld-1.0.jar
