AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Periodically polls an SQS queue and asynchronously consumes each message.
Metadata:
  Name: sqspoller
Parameters: 
  QueueNameParameter: 
    Type: String
Resources:
  sqspoller:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: >-
        Periodically polls an SQS queue and asynchronously consumes each message.
      MemorySize: 128
      Timeout: 10
      Policies:
        - SQSPollerPolicy:
            QueueName: QueueNameParameter
      Environment:
        Variables:
          queueUrl: <enter value here>
