AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application using Layers. 


Resources:

  AWS::Serverless::LayerVersion:
    Properties:
      LayerName: SampleHelloWorldLayer
      Description: Layer description
      ContentUri: nodejs/
      CompatibleRuntimes:
        - nodejs6.10
        - nodejs8.10
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain


  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: src/
    Layers:
      - !Ref SampleHelloWorldLayer