AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An Amazon S3 trigger that uses rekognition APIs to detect faces
Metadata:
  Name: rekognitionpython
Parameters:
  BucketNameParameter:
    Type: String
  CollectionIdParameter:
    Type: String
Resources:
  rekognitionpython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: An Amazon S3 trigger that uses rekognition APIs to detect faces
      MemorySize: 128
      Timeout: 3
      Policies:
        - S3CrudPolicy:
            BucketName: BucketNameParameter
        - RekognitionNoDataAccessPolicy:
            CollectionId: CollectionIdParameter
        - RekognitionWriteOnlyAccessPolicy:
            CollectionId: CollectionIdParameter
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
  Bucket1:
    Type: 'AWS::S3::Bucket'
