AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Http Api with Cors.

Globals:
  HttpApi:
    CorsConfiguration:
      AllowHeaders:
        - x-apigateway-header
      AllowMethods:
        - GET
      AllowOrigins:
        - https://foo.com
      ExposeHeaders:
        - x-amzn-header

Resources:
  HttpApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-temp-integration-tests-bucket/lambda_handler.zip
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        ImplicitApi:
          Type: HttpApi
          Properties:
            Method: GET
            Path: /path
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/'
  ApiId:
    Description: Api id of ServerlessHttpApi
    Value:
      Ref: ServerlessHttpApi
