AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Provides a simple framework for conducting various tests of your Lambda functions.
Metadata:
  Name: lambdatestharness
Parameters: 
  FunctionNameParameter: 
    Type: String
  TableNameParameter: 
    Type: String
Resources:
  lambdatestharness:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: >-
        Provides a simple framework for conducting various tests of your Lambda functions.
      MemorySize: 128
      Timeout: 60
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref FunctionNameParameter
        - DynamoDBCrudPolicy:
            TableName: !Ref TableNameParameter