name: Check interface compatibility

on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  check-interface-compatibility:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Extract original public interfaces
        run: |
          make init
          bin/public_interface.py extract >> ${{ runner.temp }}/interfaces.original.json

      - name: Backup original bin/public_interface.py
        run: |
          # Keep a copy of bin/public_interface.py to use on the base branch
          # So we are using the same bin/public_interface.py to process old/new codebase.
          # Because the step has credential of GitHub token to post comments,
          # always use the original version that is in our repository.
          cp bin/public_interface.py ${{ runner.temp }}/public_interface.py

      - name: Checkout the PR
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Extract PR public interfaces
        run: |
          echo "HEAD: $(git rev-parse --short HEAD)"
          make init
          # Recover bin/public_interface.py
          cp ${{ runner.temp }}/public_interface.py bin/public_interface.py
          bin/public_interface.py extract >> ${{ runner.temp }}/interfaces.new.json
    
      - name: Detect compatibility breaking changes
        id: detect
        run: |
          exit_code=0
          output=$(bin/public_interface.py check ${{ runner.temp }}/interfaces.original.json ${{ runner.temp }}/interfaces.new.json) || exit_code=$?

          echo "output=$output"
          echo "exit_code=$exit_code"
          echo "$output" >> $GITHUB_STEP_SUMMARY
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          echo "$output" >> ${{ runner.temp }}/output.txt

      - name: Archive interface files for debugging
        uses: actions/upload-artifact@v3
        with:
          name: interface-json-files
          path:
            - ${{ runner.temp }}/interfaces.*.json
            - output.txt
          retention-days: 7  # Only storing it for a week in case of debugging needs.

      - name: Post GitHub PR comment
        if: ${{ steps.detect.outputs.exit_code != "0" }}
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const data = fs.readFileSync('${{ runner.temp }}/output.txt', 'utf8')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "hi" + data
            })

      - name: Determine the success/failure of the workflow
        run: |
          if [ ${{ steps.detect.outputs.exit_code }} -ne 0 ]; then
            exit ${{ steps.detect.outputs.exit_code }}
          fi
