name: Update schema

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1-5"

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Update schema
        run: |
          make init
          make schema-all
    
      - name: Push change to temporary branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b tmp/schema/$GITHUB_RUN_ID/$GITHUB_RUN_ATTEMPT
          git add -u
          git commit -m "chore(schema): update"
          git push --set-upstream origin tmp/schema/$GITHUB_RUN_ID/$GITHUB_RUN_ATTEMPT

      - name: Create PR
        run: gh pr create --fill --base develop
        env:
          GH_TOKEN: ${{ github.token }}
